variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - sonarqube-chec

build:
  stage: build
  script:
    - cd ./Application/Cupid
    - ./gradlew assemble

test:
  stage: test
  script:
    - cd ./Application/Cupid
    - ./gradlew test

sonarqube-check:
  stage: sonarqube
  script:
    - cd ./Application/Cupid
    - ./gradlew test sonar