variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test

build:
  stage: build
  script:
    - cd ./Application/Cupid
    - ./gradlew assemble

test:
  stage: test
  script:
    - cd ./Application/Cupid
    - ./gradlew test
    - ./gradlew format
